name: Unitttest
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check format
      run: |
        if [ "$(go fmt | wc -l)" -gt 0 ]; then
            exit 1
        fi

    - name: Test
      run: go test -v ./...
